# ============================================================
# MEDIMANCH V6 CONCEPT MAP
#
# Important:
# These are CONCEPT UNIVERSES, not loose keywords.
# A feed record must enter through a mapped concept.
# ============================================================

CONCEPTS = {
    "backward_walking": {
        "display": "Backward Walking — log ise kyun try kar rahe hain?",
        "aliases": ["backward walking", "walking backwards", "reverse walking", "backwards walk"],
        "human_question": "People are trying backward walking. What changes when the brain has to control movement in reverse?",
        "show": "Normal walking vs backward walking, foot placement, coordination, balance and a safe public comparison.",
        "video_direction": "Peeche chalne par brain ko kaunsi extra information chahiye?",
        "behaviour_terms": ["backward walking", "walking backwards", "reverse walking", "walking"],
        "visual_actions": ["walk", "walking", "backward walking"],
        "visual_objects": [],
        "visual_tests": ["compare", "challenge", "test"],
    },
    "balance": {
        "display": "Balance Tests — aankh, kaan aur body ka teamwork",
        "aliases": ["balance test", "one leg balance", "balance challenge", "eyes closed balance", "vestibular"],
        "human_question": "Why do simple balance challenges expose how vision, inner ear and body sensing work together?",
        "show": "One-leg balance, eyes-open vs eyes-closed comparison and a safe public challenge.",
        "video_direction": "Aankh band karte hi balance itna difficult kyun ho jata hai?",
        "behaviour_terms": ["balance", "one leg", "eyes closed", "balance test", "balance challenge"],
        "visual_actions": ["balance", "stand"],
        "visual_objects": [],
        "visual_tests": ["test", "challenge", "compare"],
    },
    "flexibility": {
        "display": "Flexibility & Mobility — body kitni range use kar sakti hai?",
        "aliases": ["flexibility test", "mobility test", "range of motion", "stretching challenge", "toe touch", "deep squat", "hip mobility"],
        "human_question": "What are people actually measuring when they test flexibility or mobility?",
        "show": "Before/after range of motion, simple movement comparison and public participation.",
        "video_direction": "Flexibility aur mobility same cheez hain ya nahi?",
        "behaviour_terms": ["flexibility", "mobility", "stretching", "toe touch", "deep squat"],
        "visual_actions": ["stretch", "squat", "bend", "move"],
        "visual_objects": [],
        "visual_tests": ["test", "challenge", "compare", "range of motion"],
    },
    "breathing": {
        "display": "Breathing Hacks — nose, mouth aur breathing pattern",
        "aliases": ["breathing exercise", "breathing challenge", "nose breathing", "nasal breathing", "mouth breathing", "slow breathing", "box breathing", "breath hold"],
        "human_question": "Why are people changing their breathing pattern, and what can actually be observed?",
        "show": "Chest/abdomen movement, breathing pattern comparison and safe expert demonstration.",
        "video_direction": "Sirf breathing ka tareeka badalne se body ko kaunsa signal milta hai?",
        "behaviour_terms": ["breathing", "nose breathing", "nasal breathing", "mouth breathing", "breath hold"],
        "visual_actions": ["breathe", "breathing", "inhale", "exhale"],
        "visual_objects": [],
        "visual_tests": ["test", "challenge", "compare"],
    },
    "cold_exposure": {
        "display": "Cold Exposure — body ko thand dene ka actual response",
        "aliases": ["cold shower", "cold exposure", "ice bath", "cold water", "cold plunge", "cold therapy"],
        "human_question": "Why are people deliberately exposing themselves to cold?",
        "show": "Safe cold exposure demonstration, breathing/comfort observation and physiological explanation.",
        "video_direction": "Thande paani mein jaate hi body ka first 60-second response kya hota hai?",
        "behaviour_terms": ["cold shower", "cold exposure", "ice bath", "cold plunge", "cold water"],
        "visual_actions": ["shower", "expose", "enter"],
        "visual_objects": ["cold water", "ice", "water"],
        "visual_tests": ["compare", "test"],
    },
    "sunlight": {
        "display": "Morning Light — body clock ko daily signal",
        "aliases": ["morning sunlight", "morning light", "sunlight exposure", "early morning sunlight", "daylight", "light exposure"],
        "human_question": "Why is morning light becoming a wellness routine?",
        "show": "Morning-light timing, light/dark comparison and body-clock timeline.",
        "video_direction": "Subah ki roshni aankh se body clock tak kaise pahunchti hai?",
        "behaviour_terms": ["morning sunlight", "morning light", "sunlight", "daylight"],
        "visual_actions": ["exposure", "walk"],
        "visual_objects": ["sunlight", "light"],
        "visual_tests": ["compare"],
    },
    "sleep_routine": {
        "display": "Sleep Routine Hacks — bedtime se pehle body ko kya signal?",
        "aliases": ["sleep routine", "before bed routine", "bedtime routine", "sleep hack", "night routine", "sleep challenge"],
        "human_question": "Which bedtime behaviours are people experimenting with?",
        "show": "Routine A/B, timing, light, breathing and safe sleepiness observations.",
        "video_direction": "Sone se 60 minute pehle body ko kaunse signals milte hain?",
        "behaviour_terms": ["sleep routine", "bedtime routine", "night routine", "sleep hack", "before bed"],
        "visual_actions": ["sleep", "breathe"],
        "visual_objects": ["phone", "light", "bed"],
        "visual_tests": ["compare", "challenge"],
    },
    "meal_timing": {
        "display": "Meal Timing — same food, different time",
        "aliases": ["meal timing", "eating time", "time restricted eating", "before meal", "after meal", "empty stomach", "breakfast timing", "late dinner"],
        "human_question": "Why are people changing when they eat rather than only what they eat?",
        "show": "Meal timeline, hunger/fullness observations and research explanation.",
        "video_direction": "Same food, different time — body response kitna badal sakta hai?",
        "behaviour_terms": ["meal timing", "eating time", "empty stomach", "before meal", "after meal", "late dinner"],
        "visual_actions": ["eat", "drink"],
        "visual_objects": ["food", "meal", "plate"],
        "visual_tests": ["compare", "test"],
    },
    "fermentation": {
        "display": "Fermentation — food ko badalne se kya badalta hai?",
        "aliases": ["fermented food", "fermentation", "probiotic food", "idli fermentation", "dosa fermentation"],
        "human_question": "Why are people fermenting food, and what changes during the process?",
        "show": "Food preparation before/after fermentation, time sequence, texture and safe observable measurements.",
        "video_direction": "Ek hi food fermentation ke baad itna different kyun ho jata hai?",
        "behaviour_terms": ["fermentation", "fermented food", "ferment"],
        "visual_actions": ["ferment", "mix", "prepare"],
        "visual_objects": ["food", "jar", "batter"],
        "visual_tests": ["compare", "before after"],
    },
    "soaking_sprouting": {
        "display": "Soaking & Sprouting — food preparation ka hidden science",
        "aliases": ["soaked food", "soaking food", "overnight soaked", "sprouted", "sprouting", "soaked nuts", "soaked seeds"],
        "human_question": "Why are people soaking or sprouting nuts, seeds and grains?",
        "show": "Dry → soaked → sprouted transformation and preparation comparison.",
        "video_direction": "Bhigone se food ke andar actually kya change hota hai?",
        "behaviour_terms": ["soaked", "soaking", "sprouted", "sprouting"],
        "visual_actions": ["soak", "sprout", "prepare"],
        "visual_objects": ["nuts", "seeds", "water", "food"],
        "visual_tests": ["compare", "before after"],
    },
    "hydration": {
        "display": "Hydration Behaviours — paani kab aur kaise?",
        "aliases": ["hydration", "water intake", "drinking water", "electrolyte water", "hydration hack", "water before meal"],
        "human_question": "Which hydration hacks are people trying and what can actually be observed?",
        "show": "Water amount/timing, bottle measurements and safe hydration explanations.",
        "video_direction": "Pyaas lagne se pehle body paani ki zarurat kaise signal karti hai?",
        "behaviour_terms": ["hydration", "water intake", "drinking water", "electrolyte water"],
        "visual_actions": ["drink", "pour"],
        "visual_objects": ["water", "bottle", "glass"],
        "visual_tests": ["compare", "measure"],
    },
    "fasting": {
        "display": "Fasting Behaviours — food gap ke dauran body kya karti hai?",
        "aliases": ["fasting", "intermittent fasting", "time restricted eating", "fasting challenge"],
        "human_question": "Why are people using fasting as a routine or experiment?",
        "show": "Meal-gap timeline, hunger observations and physiology explanation.",
        "video_direction": "Last meal ke baad body ke next few hours mein kya change hota hai?",
        "behaviour_terms": ["fasting", "intermittent fasting", "fasting challenge"],
        "visual_actions": ["fast"],
        "visual_objects": ["food", "clock"],
        "visual_tests": ["challenge", "compare"],
    },
    "posture": {
        "display": "Posture Tests — body position aur movement",
        "aliases": ["posture test", "posture correction", "sitting posture", "neck posture", "forward head", "desk posture"],
        "human_question": "Why are people testing and changing their posture?",
        "show": "Side-by-side posture, movement range and safe biomechanics demonstration.",
        "video_direction": "Neck ka GPS brain ko position kaise batata hai?",
        "behaviour_terms": ["posture", "sitting posture", "neck posture", "posture test"],
        "visual_actions": ["sit", "stand", "bend"],
        "visual_objects": ["chair", "desk"],
        "visual_tests": ["test", "compare"],
    },
    "herbal_remedy": {
        "display": "Viral Herbal Remedies — nuskhe ke peeche actual mechanism",
        "aliases": ["herbal remedy", "natural remedy", "home remedy", "ayurvedic remedy", "ayurveda remedy", "herb remedy", "kadha", "churna", "nuskha", "gharelu nuskha"],
        "human_question": "Which viral herbs and home remedies are people actually trying?",
        "show": "Ingredient preparation, traditional context, safe observable properties and evidence-vs-claim separation.",
        "video_direction": "Is viral nuskhe mein actual active idea kya hai — aur claim kitna proven hai?",
        "behaviour_terms": ["herbal remedy", "natural remedy", "home remedy", "nuskha", "kadha", "churna"],
        "visual_actions": ["mix", "boil", "drink", "prepare", "apply"],
        "visual_objects": ["herb", "spice", "water", "oil", "powder"],
        "visual_tests": ["compare", "test"],
    },
    "naturopathy_pack": {
        "display": "Naturopathy Packs & Wraps — bahar se body ko signal",
        "aliases": ["naturopathy", "abdominal pack", "abdomen pack", "mud pack", "mud therapy", "wet pack", "cold pack", "hot pack", "wrap therapy", "hydrotherapy"],
        "human_question": "Why do people use packs, wraps and water-based naturopathy practices?",
        "show": "Safe preparation, temperature/pressure concept, sensation and physiology explanation.",
        "video_direction": "Pet par bahar se pack lagane se body ko kaunsa physical signal mil sakta hai?",
        "behaviour_terms": ["naturopathy", "abdominal pack", "mud pack", "wet pack", "hot pack", "cold pack", "hydrotherapy"],
        "visual_actions": ["apply", "wrap", "soak"],
        "visual_objects": ["pack", "wrap", "mud", "water", "cloth"],
        "visual_tests": ["compare", "test"],
    },
    "interoception": {
        "display": "Interoception — brain body ke andar ke signals kaise padhta hai?",
        "aliases": ["interoception", "body signals", "internal body signals", "heartbeat awareness", "hunger signal", "fullness signal", "body awareness"],
        "human_question": "Why can a body signal and a measured body state feel different?",
        "show": "Heartbeat, breathing, hunger/fullness and perception-vs-measurement demonstrations.",
        "video_direction": "Brain ko kaise pata chalta hai ki body ke andar kya ho raha hai?",
        "behaviour_terms": ["interoception", "body awareness", "heartbeat awareness", "hunger signal"],
        "visual_actions": ["breathe", "feel", "measure"],
        "visual_objects": ["timer", "heart rate monitor"],
        "visual_tests": ["test", "compare", "measure"],
    },
}

# Each YouTube query is explicitly assigned to a concept.
# This prevents the engine from guessing a concept from random words in an abstract.
YOUTUBE_QUERY_MAP = [
    ("backward walking health trend", "backward_walking"),
    ("balance test challenge health", "balance"),
    ("flexibility mobility test challenge", "flexibility"),
    ("breathing challenge wellness", "breathing"),
    ("cold shower ice bath trend", "cold_exposure"),
    ("morning sunlight health trend", "sunlight"),
    ("sleep routine before bed hack", "sleep_routine"),
    ("meal timing health trend", "meal_timing"),
    ("fermented food trend health", "fermentation"),
    ("soaked nuts seeds health trend", "soaking_sprouting"),
    ("hydration water hack trend", "hydration"),
    ("fasting challenge health trend", "fasting"),
    ("posture correction test trend", "posture"),
    ("viral herbal home remedy India", "herbal_remedy"),
    ("naturopathy pack hydrotherapy trend", "naturopathy_pack"),
    ("interoception body awareness test", "interoception"),
]

NEWS_QUERY_MAP = [
    ("backward walking health", "backward_walking"),
    ("balance challenge health", "balance"),
    ("flexibility mobility trend", "flexibility"),
    ("breathing wellness trend", "breathing"),
    ("cold exposure wellness trend", "cold_exposure"),
    ("morning sunlight sleep trend", "sunlight"),
    ("sleep routine wellness trend", "sleep_routine"),
    ("meal timing fasting trend", "meal_timing"),
    ("fermented food trend", "fermentation"),
    ("soaking sprouting food trend", "soaking_sprouting"),
    ("hydration trend wellness", "hydration"),
    ("fasting trend health", "fasting"),
    ("posture correction trend", "posture"),
    ("viral herbal home remedy", "herbal_remedy"),
    ("naturopathy hydrotherapy trend", "naturopathy_pack"),
    ("interoception body awareness", "interoception"),
]

# Research is explicitly mapped to the same concept universes.
RESEARCH_QUERY_PACKS = {
    "backward_walking": '(backward walking OR backwards walking OR reverse walking) AND humans',
    "balance": '(balance OR vestibular OR proprioception) AND humans',
    "flexibility": '(flexibility OR mobility OR range of motion OR stretching) AND humans',
    "breathing": '(breathing OR nasal breathing OR slow breathing) AND (sleep OR autonomic OR stress)',
    "cold_exposure": '(cold exposure OR cold water OR cold shower OR ice bath) AND humans',
    "sunlight": '(morning light OR daylight OR sunlight exposure) AND (circadian OR sleep)',
    "sleep_routine": '(sleep hygiene OR bedtime routine OR sleep timing) AND humans',
    "meal_timing": '("meal timing" OR eating time OR time restricted eating) AND humans',
    "fermentation": '(fermented food OR fermentation OR probiotic food) AND humans',
    "soaking_sprouting": '(sprouting OR soaking food OR seeds OR nuts) AND nutrition',
    "hydration": '(hydration OR water intake) AND humans',
    "fasting": '(intermittent fasting OR time restricted eating OR fasting) AND humans',
    "posture": '(posture OR neck position OR sitting OR biomechanics) AND humans',
    "herbal_remedy": '(herbal medicine OR plant extract OR traditional medicine) AND humans',
    "naturopathy_pack": '(hydrotherapy OR heat therapy OR cold therapy OR mud pack) AND humans',
    "interoception": '(interoception OR internal body signals) AND humans',
}

JOURNAL_FOCUS = [
    "The Lancet",
    "JAMA",
    "BMJ",
    "Nature Medicine",
    "New England Journal of Medicine",
    "Annals of Internal Medicine",
    "PLOS Medicine",
    "Gut",
    "Gastroenterology",
    "Clinical Gastroenterology and Hepatology",
    "Sleep",
    "Sleep Medicine",
    "Journal of Clinical Sleep Medicine",
    "The American Journal of Clinical Nutrition",
    "The Journal of Nutrition",
    "Obesity",
    "Diabetes Care",
    "Circulation",
    "Neurology",
    "Brain",
    "Journal of Physiology",
    "Medicine & Science in Sports & Exercise",
    "British Journal of Sports Medicine",
    "Sports Medicine",
    "Nutrients",
    "Phytomedicine",
    "Journal of Ethnopharmacology",
    "Journal of Ayurveda and Integrative Medicine",
]
