# MEDIMANCH RADAR DICTIONARY V5
# Expand this file later without changing the main app.

RADAR_DICTIONARY = {
    "behaviour": [
        "try this", "people are trying", "health hack", "wellness hack",
        "routine", "morning routine", "night routine", "before bed",
        "empty stomach", "after eating", "walking", "backward walking",
        "breathing", "holding breath", "nose breathing", "mouth breathing",
        "stretching", "rubbing", "pressing", "tapping", "shaking",
        "soaking", "boiling", "roasting", "mixing", "drinking",
        "applying", "sleeping", "fasting", "cold shower", "ice bath",
        "hot water", "sunlight", "grounding", "barefoot",
    ],
    "actions": [
        "walk", "bend", "squat", "stretch", "balance", "stand", "sit",
        "hold", "touch", "press", "rub", "tap", "breathe", "inhale",
        "exhale", "swallow", "chew", "soak", "boil", "roast", "ferment",
        "mix", "drink", "apply", "massage", "shake", "jump", "crawl",
        "sleep", "fast", "expose", "cool", "heat",
    ],
    "visual": [
        "before after", "before and after", "test", "challenge", "compare",
        "balance", "flexibility", "range of motion", "posture",
        "breathing", "pulse", "heart rate", "reaction time", "grip",
        "walk", "squat", "stretch", "movement", "ice", "heat",
        "water", "food preparation", "fermented", "soaked",
    ],
    "naturopathy": [
        "naturopathy", "hydrotherapy", "water therapy", "cold therapy",
        "heat therapy", "mud therapy", "sun bath", "sunlight therapy",
        "wet pack", "cold pack", "hot pack", "abdominal pack",
        "abdomen wrap", "clay", "mud pack", "fasting therapy",
        "nature cure", "breathing exercise", "relaxation",
    ],
    "diet_food": [
        "diet", "food", "meal", "breakfast", "dinner", "lunch",
        "empty stomach", "after meal", "before meal", "meal timing",
        "fermented", "fermentation", "soaked", "sprouted", "roasted",
        "boiled", "spice", "herb", "seed", "fruit", "vegetable",
        "protein", "fiber", "fibre", "honey", "ginger", "garlic",
        "turmeric", "cinnamon", "lemon", "salt", "vinegar",
    ],
    "self_test": [
        "self test", "home test", "simple test", "test yourself",
        "at home test", "check yourself", "balance test", "flexibility test",
        "mobility test", "breathing test", "posture test", "reaction test",
        "grip test", "sit to stand",
    ],
    "challenge": [
        "challenge", "30 day challenge", "7 day challenge", "try for",
        "do this for", "daily challenge", "experiment", "public test",
        "street test", "blind test", "compare",
    ],
    "myth_claim": [
        "myth", "fact", "does it work", "really works", "scientific",
        "science behind", "proof", "claim", "viral claim", "debunk",
        "truth", "secret", "hack", "cure", "detox",
    ],
    "effects": [
        "sleep", "energy", "digestion", "bloating", "constipation",
        "acidity", "pain", "flexibility", "balance", "memory", "focus",
        "stress", "weight loss", "appetite", "blood sugar", "metabolism",
        "recovery", "mobility", "posture", "breathing", "circulation",
        "skin", "hair",
    ],
    "ayurveda": [
        "ayurveda", "ayurvedic", "herb", "churna", "kadha", "rasayana",
        "triphala", "ashwagandha", "ginger", "turmeric", "amla",
        "jeera", "cumin", "fennel", "ajwain", "methi", "neem",
        "giloy", "brahmi", "shatavari", "vidarikand", "honey",
    ],
}

# Queries designed to discover behaviours, not just disease topics.
YOUTUBE_SEARCH_QUERIES = [
    "health hack try this",
    "wellness hack try this",
    "home remedy viral",
    "natural remedy viral",
    "before bed health hack",
    "empty stomach health hack",
    "after eating health hack",
    "food preparation health trend",
    "food challenge health",
    "self test health challenge",
    "balance test challenge",
    "flexibility test challenge",
    "breathing challenge health",
    "sleep routine viral",
    "digestion hack viral",
    "weight loss hack viral",
    "Ayurveda remedy viral",
    "naturopathy remedy",
    "health myth fact",
    "science behind viral health hack",
    "morning routine health",
    "night routine health",
    "natural sleep hack",
    "natural digestion hack",
]

# Query packs for PubMed / Europe PMC.
RESEARCH_QUERY_PACKS = {
    "breathing_sleep": '"breathing" AND (sleep OR respiration OR autonomic)',
    "food_meal_timing": '("meal timing" OR fasting OR eating time OR breakfast)',
    "fermentation_fibre": '(fermented food OR fermentation OR fiber OR fibre OR microbiome)',
    "cold_heat_water": '(cold exposure OR heat exposure OR hydrotherapy OR water)',
    "light_circadian": '(light exposure OR circadian OR sleep timing OR evening light)',
    "movement_balance": '(balance OR proprioception OR mobility OR biomechanics OR walking)',
    "gut_sensation": '(gut sensation OR interoception OR gastric distension OR bloating)',
    "natural_remedies": '(herbal medicine OR plant extract OR traditional medicine)',
    "fasting": '(fasting OR time restricted eating OR caloric restriction)',
    "hydration": '(hydration OR water intake OR fluid balance)',
    "posture": '(posture OR sitting OR neck position OR musculoskeletal)',
    "stress_recovery": '(stress OR relaxation OR recovery OR autonomic nervous system)',
    "self_testing": '("self test" OR screening OR home test OR functional test)',
}

# Google News queries: these are intentionally behaviour/visual-first.
VISUAL_SIGNAL_QUERIES = [
    "viral health hack",
    "viral wellness hack",
    "people trying health trend",
    "health challenge trend",
    "home remedy trend",
    "natural remedy trend",
    "viral diet trend",
    "food preparation trend health",
    "self test health trend",
    "balance challenge health",
    "breathing challenge",
    "sleep routine trend",
    "walking trend health",
    "stretching trend health",
    "cold water trend health",
    "Ayurveda trend",
    "naturopathy trend",
    "traditional remedy trend",
]

# Authoritative journal watchlist.
# PubMed is used as the retrieval layer, so no fragile individual RSS URL is required.
JOURNAL_FOCUS = [
    "The Lancet",
    "JAMA",
    "BMJ",
    "Nature Medicine",
    "New England Journal of Medicine",
    "Annals of Internal Medicine",
    "PLOS Medicine",
    "Gut",
    "Gastroenterology",
    "Clinical Gastroenterology and Hepatology",
    "Sleep",
    "Sleep Medicine",
    "Journal of Clinical Sleep Medicine",
    "The American Journal of Clinical Nutrition",
    "The Journal of Nutrition",
    "Obesity",
    "Diabetes Care",
    "Hypertension",
    "Circulation",
    "Neurology",
    "Brain",
    "Journal of Physiology",
    "Medicine & Science in Sports & Exercise",
    "British Journal of Sports Medicine",
    "Sports Medicine",
    "Nutrients",
    "Phytomedicine",
    "Journal of Ethnopharmacology",
    "Journal of Ayurveda and Integrative Medicine",
]
